---
apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  annotations:
    kommander.mesosphere.io/description: "Project space for NKPChampion resources"
    kommander.mesosphere.io/display-name: "NKPChampion Project"
  name: nkpchampion
  namespace: zy
spec:
  namespaceName: nkpchampion
  placement:
    clusters:
    - name: zy-nkp-wkld
  workspaceRef:
    name: zy
